Repository go-kratos/gateway, pull requests merged in 2024-03, with the labels that each got.

#222 fix: remove unnecessary "http.Handler" #221
  proxy/proxy.go
Labels: size:XS, lgtm

#217 priority config
  api/gateway/config/v1/gateway.pb.go
  api/gateway/config/v1/gateway.proto
  api/gateway/middleware/circuitbreaker/v1/circuitbreaker.pb.go
  api/gateway/middleware/cors/v1/cors.pb.go
  api/gateway/middleware/logging/v1/logging.pb.go
  api/gateway/middleware/rewrite/v1/rewrite.pb.go
  api/gateway/middleware/tracing/v1/tracing.pb.go
  cmd/gateway/main.go
  config/config-loader/ctrl-loader.go
  config/config.go
Labels: size:XL, lgtm

#226 protect internal handler
  proxy/debug/debug.go
  router/mux/mux.go
Labels: size:S, lgtm
